version: "3.2"
services:
  activemq:
    image: symptoma/activemq:latest
    container_name: activemq
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
    - ./activemq.xml:/opt/activemq/conf/activemq.xml